### PR TITLE
Streamed PK-based encryption and decryption

### LINKED ISSUE #424: Implement streamed data processing
## Description

Within current implementation data is processed as a whole and processing results are stored in memory for later processing. So memory usage is a multiply of input size, which is wrong - it must be (and could be) constant except some rare circumstances (when we don't have one-pass signature? don't remember for sure right now).

So we need to switch to streamed processing, so input data will be handle like the following:
- input file is read to memory by chunks (say, 64k blocks)
- it is parsed and according to contents or operation data processors are created
- and this chunk of data passes through all processors up to the output file/memory/stdout

Say, for instance, for file encryption it could be like this:
- file_processor - processor which starts the chain and reads file by chunks in cycle
- data_hash_calculator for MDC
- data_compressor
- data_encryptor
- file_writer

For PGP data processing it would be a bit different since we don't know the packet contents from the beginning, so should insert some 'decision makers' which parse data and create processors on the go.

It could be divided into the following parts:

- [x] Implement streamed processing for symmetric encryption and decryption
- [x] Implement armouring/dearmouring streams
- [x] Move existing PK encryption and decryption to streamed processing
- [x] Implement streamed signing and verification of attached signatures
- [x] Implement streamed signing/verification for detached signatures
- [x] Implement streamed cleartext signing/verification

### PR DESCRIPTION
**Pull request by ni4**
This PR completely moves encrypt and decrypt commands (including password-only encryption) to the streamed approach.
Also it makes rnp ready for multiple-recipient encryption and decryption, just some minor CLI modifications are required.
It doesn't remove old encrypt/decrypt functionality - I think it would be better to remove it when signing/verification and cleartext operations will be updated to use streamed approach as well.

It is the part of the issue #424

### CODE REVIEW

File: src/rnp/rnp.c [hunk 1]
```diff
@@ -393,24 +381,13 @@ rnp_cmd(rnp_cfg_t *cfg, rnp_t *rnp, int cmd, char *f)
...
-        if (f) {
-            const char *out = rnp_cfg_get(cfg, CFG_OUTFILE);
-            repgp_set_input(io, create_filepath_handle(f));
-            repgp_set_output(io, create_filepath_handle(out));
-        } else {
-            repgp_set_input(io, create_stdin_handle());
-            repgp_set_output(io,
-                             create_buffer_handle((size_t) rnp_cfg_getint(cfg, CFG_MAXALLOC)));
-        }
-        ret = (RNP_SUCCESS == repgp_decrypt(&ctx, io));
```
Comment (flowher) [inline src/rnp/rnp.c]: I would rather see ``rnp_process_stream`` called by ``repgp_decrypt``.  Also implementation from ``init_stdin_src`` needs to be moved to ``create_stdin_handle`` as it's obviously duplicated now.

File: src/librepgp/stream-parse.c [hunk 2]
```diff
@@ -568,114 +503,183 @@ encrypted_src_close(pgp_source_t *src)
...
+        err = pgp_sm2_decrypt(decbuf,
+                              &declen,
+                              sesskey->params.sm2.m,
+                              sesskey->params.sm2.mlen,
+                              &seckey->key.ecc,
+                              &seckey->pubkey.key.ecc);
+
+        if (err != RNP_SUCCESS) {
+            (void) fprintf(
+              stderr, "%s: SM2 decryption failure, error %x\n", __func__, (int) err);
```
Comment (flowher) [inline src/librepgp/stream-parse.c]: ``RNP_LOG`` please (or at least same output)

File: src/librepgp/stream-parse.c [hunk 3]
```diff
@@ -568,114 +503,183 @@ encrypted_src_close(pgp_source_t *src)
...
+                                     &declen,
+                                     sesskey->params.ecdh.m,
+                                     sesskey->params.ecdh.mlen,
+                                     ecdh_p,
+                                     &seckey->key.ecc,
+                                     &seckey->pubkey.key.ecdh,
+                                     &fingerprint);
+        BN_free(ecdh_p);
+
+        if ((err != RNP_SUCCESS) || (declen > INT_MAX)) {
```
Comment (flowher) [inline src/librepgp/stream-parse.c]: check on ``declen`` is not needed

File: src/librepgp/stream-parse.c [hunk 4]
```diff
@@ -568,114 +503,183 @@ encrypted_src_close(pgp_source_t *src)
...
+        return true;
+    } else {
+        return false;
+    }
+}
 
-    switch (skey->s2k.specifier) {
-    case PGP_S2KS_SIMPLE:
+static bool
+encrypted_try_key(pgp_source_t *src, pgp_pk_sesskey_pkt_t *sesskey, pgp_key_t *key)
```
Comment (flowher) [inline src/librepgp/stream-parse.c]: This function is partially copy paste of ```pgp_create_pk_sesskey()```. Can you reuse the code which already exist?

Comment (ni4) [reply src/librepgp/stream-parse.c]: Yeah, I borrowed code from old places. The reason I don't reuse old functions is that they use other input/output model and don't follow the 'dump entities' logic, i.e. packet struct is just a parsed OpenPGP entity without any additional data like decrypted keys, flags, and so on. Once transition to the streams is finished all old code and old functions will be removed.

Comment (flowher) [reply src/librepgp/stream-parse.c]: ok. I see, that's just for transition time

File: src/librepgp/stream-parse.c (hunk 2 above)
Comment (ronaldtse) [reply src/librepgp/stream-parse.c]: Agree

File: src/rnp/rnp.c (hunk 1 above)
Comment (ronaldtse) [reply src/rnp/rnp.c]: @ni4 what's your plan regarding `librepgp` API in the streamed approach?

File: src/librepgp/stream-parse.c (hunk 3 above)
Comment (ni4) [reply src/librepgp/stream-parse.c]: Thanks, fixed.

File: src/librepgp/stream-parse.c (hunk 4 above)
Comment (ni4) [reply src/librepgp/stream-parse.c]: Agree, added #490

File: src/librepgp/stream-parse.c (hunk 2 above)
Comment (ni4) [reply src/librepgp/stream-parse.c]: Okay, will update the PR

File: src/librepgp/stream-parse.c [hunk 5]
```diff
@@ -1026,22 +1006,54 @@ init_encrypted_src(pgp_processing_ctx_t *ctx, pgp_source_t *src, pgp_source_t *r
...
+        keyctx.stype = PGP_KEY_SEARCH_KEYID;
+
+        for (int i = 0; i < param->pubencc; i++) {
+            memcpy(keyctx.search.id, param->pubencs[i].key_id, sizeof(keyctx.search.id));
+            /* Get the key if any */
+            if (!pgp_request_key(ctx->handler.key_provider, &keyctx, &seckey)) {
+                continue;
+            }
+            /* Unlock key */
+            if (!pgp_key_unlock(seckey, ctx->handler.passphrase_provider)) {
```
Comment (dewyatt) [inline src/librepgp/stream-parse.c]: Since this isn't really a CLI-layer function, I would rather we didn't use `pgp_key_unlock`.
Normally what I would do is decrypt the seckey into a separate temporary variable and dispose of it at the end, like:
https://github.com/riboseinc/rnp/blob/master/src/lib/generate-key.c#L484

My intention for the use of `pgp_key_unlock` was always mainly FFI/API clients (and CLI would be OK too).
The general idea is:

* call `sign()` (as an example)
  * the key is already unlocked, so it is used as-is, or:
  * the key is locked, so it is temporarily decrypted and used, then disposed of

So in the case of a protected+locked key (should be the most common case), the decrypted MPIs are only exposed for a minimum window of time.

File: src/librepgp/stream-parse.c [hunk 6]
```diff
@@ -1063,8 +1076,11 @@ init_encrypted_src(pgp_processing_ctx_t *ctx, pgp_source_t *src, pgp_source_t *r
                 goto finish;
             }
         } while (1);
-    } else {
-        errcode = RNP_ERROR_NOT_SUPPORTED;
+    }
+
+    if (!have_key) {
+        (void) fprintf(stderr, "%s: failed to obtain decrypting key or password\n", __func__);
```
Comment (dewyatt) [inline src/librepgp/stream-parse.c]: We should try to return an appropriate error code here. Currently this logs to the console when I use an incorrect passphrase, for example. I believe this function would be used by FFI clients, so ideally we would not do that here, but at the call site.

File: src/rnp/rnp.c (hunk 1 above)
Comment (ni4) [reply src/rnp/rnp.c]: @ronaldtse @flowher I think at first I will finish all further stream-based code and then we'll decide how to better glue it with repgp. Actually, it will be just one call for data parsing - rnp_process_stream, outputting decrypted/verified data and giving other information (like signatures) via the callback.

File: src/librepgp/stream-parse.c (hunk 5 above)
Comment (ni4) [reply src/librepgp/stream-parse.c]: Thanks. Looks like I mislooked the purpose of unlock or was in hurry. Will fix this.

Comment (ni4) [reply src/librepgp/stream-parse.c]: @dewyatt `pgp_seckey_free_secret_mpis` doesn't scrub/zero mpi contents, just calls `botan_mp_destroy`. Does it clear the contents?

File: src/rnp/rnp.c (hunk 1 above)
Comment (ronaldtse) [reply src/rnp/rnp.c]: 👍

File: src/librepgp/stream-parse.c (hunk 5 above)
Comment (dewyatt) [reply src/librepgp/stream-parse.c]: @ni4 Generally yes `botan_mp_destroy` will scrub that memory. See [here](https://botan.randombit.net/manual/side_channels.html#memory-allocation). The MP FFI interface is backed by botan's `BigInt`, which uses `secure_vector`, so that memory is scrubbed when freed.

**Comment by ni4** [comment]
@dewyatt @flowher I addressed all your comments in the last commits. Do you have any further suggestions?

**Comment by flowher** [comment]
Nop, this looks GTM
