### PR TITLE
Fix signing/encryption with default key

### LINKED ISSUE #682: rnp --sign doesn't work without the username parameter
## Description

While rnp should be able to use default key for signing, it doesn't.

## Steps to Reproduce

`rnp --sign somefile`

### PR DESCRIPTION
**Pull request by ni4**
Recently signing/encryption with not specified signer/recipient was broken so this PR fixes it.
Also, in order to cover updated code, I added cmocka CLI test and some overhead to allow call rnp.cpp:main from the rnp_tests.
It uses define `RNP_TESTS`, which is set in `CMakeLists.txt` for `rnp_tests` target.
@dewyatt , @ronaldtse what do you think about such approach?
It would allow to add more tests later on and improve coverage and static analysis on rnp/rnpkeys

Fixes #682

### CODE REVIEW

**Comment by ni4** [comment]
@dewyatt Agree, will update now to RNP_RUN_TESTS.
Btw, I believed that codecov does coverage for `rnp_tests` run but according to diff rnp/rnpkeys was also covered. I.e. does it calculate coverage for runs via python cli_tests, or I just mislooked something?

**Comment by dewyatt** [comment]
> Btw, I believed that codecov does coverage for rnp_tests run but according to diff rnp/rnpkeys was also covered. I.e. does it calculate coverage for runs via python cli_tests, or I just mislooked something?

It does both `rnp_tests` and `cli_tests`. They are done in two separate jobs in CI and then codecov merges that info.

File: src/rnp/rnp.cpp [hunk 1]
```diff
@@ -856,8 +866,8 @@ main(int argc, char **argv)
                 rnp_cfg_setstr(&cfg, CFG_SSHKEYFILE, optarg);
                 break;
             case 'V':
-                print_praise();
-                exit(EXIT_SUCCESS);
+                setcmd(&cfg, CMD_VERSION, optarg);
```
Comment (dewyatt) [inline src/rnp/rnp.cpp]: Shouldn't this check the return value now?

**Comment by ni4** [comment]
@dewyatt Thanks for explanation. I updated the latest commit with new define name

File: src/rnp/rnp.cpp [hunk 2]
```diff
@@ -906,6 +919,15 @@ main(int argc, char **argv)
         }
     }
 
+    switch (rnp_cfg_getint(&cfg, CFG_COMMAND)) {
+    case CMD_HELP:
+    case CMD_VERSION:
+        rnp_cmd(&cfg, &rnp);
+        ret = EXIT_SUCCESS;
```
Comment (dewyatt) [inline src/rnp/rnp.cpp]: Should this be conditional based on the return of `rnp_cmd`?

File: src/rnp/rnp.cpp (hunk 1 above)
Comment (ni4) [reply src/rnp/rnp.cpp]: Generally - yes. I allowed it here because CMD_VERSION/CMD_HELP always succeed. But you are right, it is better to add checks.

File: src/rnp/rnp.cpp (hunk 2 above)
Comment (ni4) [reply src/rnp/rnp.cpp]: The same as previous. Will update the PR shortly.

File: src/rnp/rnp.cpp (hunk 1 above)
Comment (ni4) [reply src/rnp/rnp.cpp]: Argh, sorry, misunderstood the question. Here it will just set the command, return value will be checked below (the next your comment).

Comment (ni4) [reply src/rnp/rnp.cpp]: Omg, no. I will get back to this tomorrow. Too late at the evening to think well.
Only now got what did your comment actually mean :-)

**Comment by ni4** [comment]
@dewyatt Please see the latest commit. It should fix the issues you described.

File: src/tests/cli.cpp [hunk 3]
```diff
@@ -0,0 +1,79 @@
...
+#include "utils.h"
+
+int rnp_main(int argc, char **argv);
+
+int
+call_rnp(const char *cmd, ...)
+{
+    int     argc = 0;
+    int     res;
+    char ** argv = (char **) calloc(32, sizeof(char *));
```
Comment (dewyatt) [inline src/tests/cli.cpp]: Might be a good place to start using C++ (just a simple `std::string` on the stack).
